server:
  port: 8080
  host: 0.0.0.0

database:
  host: "{{qa_postgres_DbHost}}"
  port: 5432
  username: "{{qa_postgres_DbUser}}"
  password: "{{qa_postgres_DbPswd}}"
  database: auto_citadel_central
  sslmode: prefer
  maxOpenConnection: 100
  maxIdleConnection: 10

redis:
  pubsub:
    address: "redis.default.svc.cluster.local:6379"
    password: ""
    db: 32
    poolsize: 10
    minidle: 1
  address: "redis.default.svc.cluster.local:6379"
  password: ""
  db: 30

cors_allow_origin:
  - https://auto-porte-api.qa.orangehealth.dev
  - http://localhost:8222/

sentry:
  dsn: ""

env: dev

service_name: citadel-central

aws:
  bucket: auto-oms-orders
  S3_AWS_ACCESS_KEY_ID: "{{qa_awsS3AccessKeyId}}"
  S3_AWS_SECRET_ACCESS_KEY: "{{qa_awsS3SecretAccessId}}"
  SQS_AWS_ACCESS_KEY_ID: "{{qa_awsS3AccessKeyId}}"
  SQS_AWS_SECRET_ACCESS_KEY: "{{qa_awsS3SecretAccessId}}"
  AWS_REGION: ap-south-1
  SQS_QUEUE_URL: "https://sqs.ap-south-1.amazonaws.com/606514307308/auto-citadel-consumer-central.fifo"
  SQS_STANDARD_QUEUE_URL: "https://sqs.ap-south-1.amazonaws.com/606514307308/auto-citadel-consumer-central"
  SNS_AWS_ACCESS_KEY_ID: "{{qa_awsS3AccessKeyId}}"
  SNS_AWS_SECRET_ACCESS_KEY: "{{qa_awsS3SecretAccessId}}"

cds:
  api_key: U8vtE9WzcJw0bMPTH67fnyRx
  base_url: http://cds-api
  user_email: shrish.chandra@orangehealth.in

worker:
  broker: "https://sqs.ap-south-1.amazonaws.com/606514307308"
  default_queue: auto-citadel-worker-central
  default_queue_fifo: auto-citadel-worker-central.fifo
  result_backend: "redis://redis.default.svc.cluster.local:6379/41"
  redis_pool_size: ""
  redis_max_idle: ""
  processes: 10

doctor_tat_duration: 30

active_city_codes:
  - BLR
  - DEL
  - NOA
  - HYD
  - MUM
  - NRL

oms:
  base_url: http://oms-router-api
  api_key: "OF4599TtM5JX73ZdUeJNkPj2"
  base_domain: https://auto-oms-city_code.qa.orangehealth.dev
  incoming_api_key: "OF4599TtM5JX73ZdUeJNkPj2"

topics:
  order_report_update: "arn:aws:sns:ap-south-1:606514307308:auto_order_results_update.fifo"
  order_results_approved: "arn:aws:sns:ap-south-1:606514307308:auto-order-results-approved.fifo"
  contact_merge_confirm: "arn:aws:sns:ap-south-1:606514307308:auto-contact-merge-confirm"
  ets_test_event: "arn:aws:sns:ap-south-1:606514307308:auto-scheduler-task-updates.fifo"
  report_ready: "arn:aws:sns:ap-south-1:606514307308:auto-report-ready.fifo"
  oms_updates: "arn:aws:sns:ap-south-1:606514307308:auto-oms-consumer"
  citadel: "arn:aws:sns:ap-south-1:606514307308:auto-citadel-updates"

s3wrapper:
  base_url: http://s3wrapper-api
  api_key: jokaQ6c1jmpfLbXyyV1x1jT9

cron_frequencies:
  stale_tasks_periodic_task: "* * * * *"
  ets_tat_breached_frequency: "*/5 * * * *"
  slack_alert_for_reverse_logistics_frequency: "1,31 * * * *"

report_rebranding:
  base_url: http://report-rebranding-api
  token: "HAlo67JHJ8hjsdjJKHK6786H87jkjklhjdsLSDKL"

patient_service:
  base_url: http://patients-api
  api_key: "aksjcbkajc"

attune:
  api_base_url: https://orange-uat.attunelive.net/OrangeUAT-API/api
  username: Orange Diagnostics
  password: Orange Diagnostics
  client_id: Orange Diagnostics
  org_code: Orange Diagnostics
  result_file_type: string
  incoming_api_key: yTzGKEdbeN4NUV4d42bduDt3XbVactQB
  client_secret: nEBJAd87V2eoAXcp44VFMc5b%2BSfO87n%2BPZKHMxBeB7kxL63FiQCVD49vgPh0aYnVRgccwJvks3oMCkvnDB9eZ4PXVhjKj%2Bct2QQXQQXlqN4SaucELDHx%2Bi4XO3aWmJPcgCZbf6rjccUO8Ffe5H7W4DO5pevPqZH5CzQyy6oEXI3NnksLsqwcZDLIzweytrro2vZTyA11Bd47lYi4I%2BpJud9ZZL2PbudhQsBw6%2FnEw88WIw1FzUxepYcduCFHGSEN%2Fyl%2B317GBkRFjEnrhOTG1CyeNZYhOtAh7oga8VTNqwgCJK7l%2BPRbBz0oOR4jmHgHivEonXjHlvFtSWDUz%2BeP4LQdeym%2FPbaYJ%2BiBDF%2BrQavtEJko8ZrbO%2BEEZ%2B7Z6IjqE40MlwmfeGLwNiU2qpLBxmYac3BDi1KWGkfDeZ9dDvk9Y%2FO8qH%2B9kwCAyGp2STagOViQ8daJkCeqBVL1KpdAct3AeaLL3YsC1CDzDWc49F5FEYky7AF1hIosBb7Dwwpo00LFjB7oYQO9w9jttDrawEP4j4gbuwNWYZu6Rb%2BZycnkz%2BnDP5nv8HyuYesEL24ukNLQOVoT0geagzG86ygQ72L8YMJSOdaRq%2B9vqe2CrPnPA3gyPIa8zDLxgVKkTROy4j5m5vhquFgpFbafv9%2Bxq79HRcE3S4tcFyhGhUjNYa4T7dX8fO%2BQQYkvwoLvAyhwwtTUDkos4aXW595F15f7CqR9atzdGK98qWi%2BpOIO3PlnUnmq3qnAkpJN2D2cAPGE6wkQGCtrfdlh20gvXHZ545Me7l75kmZ%2Bc%2FsJj%2FQ1G%2FTzMLdMlF5%2BWnptB%2Flol2X1uA%3D%3D
  org_codes:
    1: Orange Diagnostics
    10: Orange Health Diagnostic Gurgaon
    21: Orange Health Diagnostic Lab
    33: Orange Health Hyderabad Lab
    52: Orange Health Mumbai
    67: Orange NRL Bangalore
    117: Orange Health Bangalore 2 (North)

security:
  jwt_secret: "fuhvbsudfbuvbdfuhvbbu34wref98498brefds"
  url_paths_to_skip_jwt_auth:
    - /ping/
    - /api/v1/users/get-user-by-email/
    - /api/v1/external-investigation-results/bulk-upsert
    - /api/v1/external-investigation-results/bulk-delete
    - /api/v1/external-investigation-results/
    - /api/v1/test-details/oms-test/lab-id
    - /api/v1/test-sample-mapping/sample-number
    - /api/v1/samples/add-barcode
    - /api/v1/samples/add-barcode-for-orangers
    - /api/v1/samples/update-task-sequence
    - /api/v1/samples/update-sample-details-for-reschedule
    - /api/v1/samples/scheduler/sample-details
    - /api/v1/samples/scheduler/update-sample-details
    - /api/v1/samples/order-details
    - /api/v1/search/info-screen/barcode/
    - /api/v1/search/info-screen/order/
    - /api/v1/search/info-screen/visit/
    - /api/v1/search/barcode-details/
    - /api/v1/samples/request-details
    - /api/v1/samples/remap-samples
    - /api/v1/samples/oms-test-details
    - /api/v1/samples/delayed-samples-reverse-logistics
    - /api/v1/samples/srf-order-ids
    - /api/v1/report-generation/trigger
    - /api/v1/report-generation/trigger-order-approved-event
    - /api/v1/samples/collect-volume
    - /api/v1/samples/mark-sample-accessioned
    - /api/v1/tasks/orders/

porte:
  incoming_api_key: "u9Ua7W6TRFvXTwY99CR6ucgB"

groot:
  incoming_api_key: "mynameisgroot"

ets:
  incoming_api_key: "shrish"

citadel_system_id: 23

lis_system_id: 24

stale_task_duration: 10

auto_approval_ids_map:
  BLR: 25
  DEL: 25
  MUM: 25
  HYD: 25
  NOA: 25
  NRL: 25

health_api:
  base_url: http://health-api
  api_key: "abcd"
  incoming_api_key: "healthymoment"

accounts_api:
  base_url: http://accounts-api
  api_key: "c2hyaXNo"

partner_api:
  base_url: http://partner-api
  api_key: "eL4JwCKSjFNxXxZ2t5CuqJ86Rz"

slack:
  base_url: https://slack.com
  token: "xoxb-1134590247201-1267368119234-oONY7gXt4Q2BW1ksOMRjA8PF"
  report_sync_failures_channel: report-sync-failures-blr
  missing_parameters_channel: missing-tests-investigations
  auto_approval_failures_channel: report-sync-failures-blr

receiving_desk:
  multiple_orders_enabled: true

duty_doctor:
  sunday:
    shift_1:
      start_time: 7:00
      end_time: 16:00
      doctor:
        BLR: 1365385
        DEL: 1327113
        HYD: 759396
        MUM: 238349
        NOA: 1414615
        NRL: 349887
    shift_2:
      start_time: 16:00
      end_time: 7:00
      doctor:
        BLR: 1186492
        DEL: 759343
        HYD: 759396
        MUM: 238349
        NOA: 759343
        NRL: 39927
  monday:
    shift_1:
      start_time: 7:00
      end_time: 16:00
      doctor:
        BLR: 1365385
        DEL: 1327113
        HYD: 759396
        MUM: 238349
        NOA: 1414615
        NRL: 349887
    shift_2:
      start_time: 16:00
      end_time: 7:00
      doctor:
        BLR: 1186492
        DEL: 759343
        HYD: 759396
        MUM: 238349
        NOA: 759343
        NRL: 39927
  tuesday:
    shift_1:
      start_time: 7:00
      end_time: 16:00
      doctor:
        BLR: 1365385
        DEL: 1327113
        HYD: 759396
        MUM: 238349
        NOA: 1414615
        NRL: 349887
    shift_2:
      start_time: 16:00
      end_time: 7:00
      doctor:
        BLR: 1186492
        DEL: 759343
        HYD: 759396
        MUM: 238349
        NOA: 759343
        NRL: 39927
  wednesday:
    shift_1:
      start_time: 7:00
      end_time: 16:00
      doctor:
        BLR: 1365385
        DEL: 1327113
        HYD: 759396
        MUM: 238349
        NOA: 1414615
        NRL: 349887
    shift_2:
      start_time: 16:00
      end_time: 7:00
      doctor:
        BLR: 1186492
        DEL: 759343
        HYD: 759396
        MUM: 238349
        NOA: 759343
        NRL: 39927
  thursday:
    shift_1:
      start_time: 7:00
      end_time: 16:00
      doctor:
        BLR: 1365385
        DEL: 1327113
        HYD: 759396
        MUM: 238349
        NOA: 1414615
        NRL: 349887
    shift_2:
      start_time: 16:00
      end_time: 7:00
      doctor:
        BLR: 1186492
        DEL: 759343
        HYD: 759396
        MUM: 238349
        NOA: 759343
        NRL: 39927
  friday:
    shift_1:
      start_time: 7:00
      end_time: 16:00
      doctor:
        BLR: 1365385
        DEL: 1327113
        HYD: 759396
        MUM: 238349
        NOA: 1414615
        NRL: 349887
    shift_2:
      start_time: 16:00
      end_time: 7:00
      doctor:
        BLR: 1186492
        DEL: 759343
        HYD: 759396
        MUM: 238349
        NOA: 759343
        NRL: 39927
  saturday:
    shift_1:
      start_time: 7:00
      end_time: 16:00
      doctor:
        BLR: 1365385
        DEL: 1327113
        HYD: 759396
        MUM: 238349
        NOA: 1414615
        NRL: 349887
    shift_2:
      start_time: 16:00
      end_time: 7:00
      doctor:
        BLR: 1186492
        DEL: 759343
        HYD: 759396
        MUM: 238349
        NOA: 759343
        NRL: 39927

investigation:
  enable_auto_approval_slack_alerts: true
  abnormality_whitelisted_master_investigation_ids:
    - 287
    - 61
  delta_check_whitelisted_master_investigation_ids:
    - 53
    - 151
    - 239
    - 240
    - 241
    - 243

superlab:
  base_url: https://auto-superlab-central.qa.orangehealth.dev

master_tests:
  covid_rtpcr_ids:
    - 461
