name: Validate Config Keys
on:
  pull_request:
    branches:
      - main

jobs:
  validate-keys:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Install Dependencies
        run: go mod tidy -compat=1.22.3

      - name: Debug File Structure
        run: ls -R config/

      - name: Run Config Validation
        run: go mod tidy -go=1.22.3 && go run .github/scripts/validate_structure.go
